#!/usr/bin/env python3
"""Expedite Alerts Generator.

Reads the risk report (from extract_risks.py) and config-bundle.json,
applies ignore rules, mapping configurations, and generates personalized
expedite alert text for each assigned employee.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

def load_json(path: Path) -> Any:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))

def is_ignored(ignore_list: list[str], zh_name: str, en_name: str) -> bool:
    zh = (zh_name or "").lower()
    en = (en_name or "").lower()
    for word in ignore_list:
        w = word.lower()
        if w in zh or w in en:
            return True
    return False

def format_expedite_source_label(mode: str) -> str:
    if mode == "rectification": return "【安全整改】"
    if mode == "special": return "【CPT专项风险】"
    if mode == "risk": return "【常规风险】"
    if mode == "vulnerability": return "【漏洞预警】"
    if mode == "sr": return "【SR详单监控】"
    return "【其他】"

def translate_ticket_title(mode: str, row: dict[str, Any]) -> str:
    if mode == "sr":
        return row.get("sr_num", "Unknown SR")
    if mode == "vulnerability":
        return row.get("vulnerability_id") or row.get("vuln_id") or row.get("漏洞编号", "Unknown Vuln")
    if mode in ["rectification", "risk", "special"]:
        return row.get("问题标题-Title") or row.get("问题标题") or row.get("title", "Unknown Ticket")
    return "Unknown Ticket"

def get_employee_mapping(welink_policy: dict[str, Any]) -> dict[str, dict[str, Any]]:
    roster = welink_policy.get("roster", [])
    assignments = welink_policy.get("assignments", {})
    mapping = {}
    for person in roster:
        emp_id = person["id"]
        mapping[emp_id] = {
            "name": person["name"],
            "assignments": [cat for cat, emps in assignments.items() if emp_id in emps],
            "alerts": []
        }
    return mapping

def main():
    parser = argparse.ArgumentParser(description="Generate personalized expedite alerts.")
    parser.add_argument("--risk-report", required=True, help="Path to risk_report.json generated by extract_risks.py")
    parser.add_argument("--config", required=True, help="Path to config-bundle.json")
    parser.add_argument("--output", default="alerts_output.json", help="Output JSON for alerts")
    parser.add_argument("--output-ps1", default="", help="Optional output path for a runnable PowerShell script (e.g. push.ps1)")
    args = parser.parse_args()

    risk_report = load_json(Path(args.risk_report))
    config = load_json(Path(args.config))

    report_config = config.get("report_config", {})
    welink_policy = report_config.get("welink_policy_v2", {})
    prefs = config.get("prefs", {})
    global_expedite_prefs = prefs.get("global_expedite", {})
    
    ignore_list = global_expedite_prefs.get("ignoreKeywords", [])
    templates = report_config.get("welink_template_config", {})
    
    if not templates:
        templates = {
            "title": "⚡ 交付质量红线督办预警",
            "greeting": "【{emp_name}】您好，您负责的代表处/业务线下存在临期或超期的高危风险数据：",
            "footer": ">> 请各位总干事重点跟进以上超期和高危单据并尽快闭环，该通报结果将于月末直接折算计入部门总分。系统自动通报，请勿回复。"
        }
    
    emp_mapping = get_employee_mapping(welink_policy)
    
    # Group items by group -> category
    # Actually, assignment is by group_id or category_id. The frontend says "assignSelectedTo(catId)".
    # assignments array looks like: ["cat_5", "cat_12"] etc.
    # In tools-platform, categories are basically metric names or 'SR详单'.
    # For simplicity, we just check if the risk item's 'customer_name' or 'rep_office' matches the category.
    # Actually, let's just group them exactly how expedite.js does it.
    
    # We will put all risks into a flat list, mapped to assignments
    # In expedite.html, it maps via `GlobalMetrics` and `customer_name_cn` etc.
    # Since we don't have the full browser context, we will assign any risk row whose `customer_name`, `country_name_cn`, or `repoffice_name_cn` exactly matches the assignment string.
    
    for file_name, data in risk_report.items():
        mode = data.get("mode")
        for row in data.get("danger_items", []) + data.get("warning_items", []):
            zh_name = row.get("customer_name") or row.get("country_name_cn") or row.get("repoffice_name_cn") or "Global"
            en_name = row.get("vulnerability_name") or row.get("sr_num") or "Ticket"
            
            if is_ignored(ignore_list, zh_name, en_name):
                continue
            
            sla_text = row.get("_slaText", "")
            title = translate_ticket_title(mode, row)
            line = f" {format_expedite_source_label(mode)} {title} ({sla_text})"
            
            # Find who owns this
            assigned = False
            for emp_id, emp_data in emp_mapping.items():
                if any(cat in zh_name for cat in emp_data["assignments"]) or any(cat.startswith("GLOBAL") for cat in emp_data["assignments"]):
                    emp_data["alerts"].append(line)
                    assigned = True
            
            if not assigned:
                # Assign to a default unassigned bucket
                if "unassigned" not in emp_mapping:
                    emp_mapping["unassigned"] = {"name": "Unassigned", "alerts": []}
                emp_mapping["unassigned"]["alerts"].append(line)

    results = {}
    ps1_lines = [
        "[Console]::OutputEncoding = [System.Text.Encoding]::UTF8",
        "$OutputEncoding = [System.Text.Encoding]::UTF8",
        "",
        "Write-Host \"🔄 正在检查并刷新 WeLink 认证状态 (防 401 假死)...\" -ForegroundColor Cyan",
        "$statusOutput = welink-cli auth status 2>&1 | Out-String",
        "$envParam = \"\"",
        "if ($statusOutput -match \"Environment:\\s*pro\") { $envParam = \"--env pro\" }",
        "Write-Host \"> welink-cli auth login $envParam\" -ForegroundColor DarkCyan",
        "Invoke-Expression \"welink-cli auth login $envParam\"",
        "",
        "Write-Host \"🚀 开始执行自动化分发任务...\" -ForegroundColor Green"
    ]

    for emp_id, emp_data in emp_mapping.items():
        if not emp_data["alerts"]:
            continue
        
        greeting = templates.get("greeting", "【{emp_name}】您好：").replace("{emp_name}", emp_data["name"])
        body = "\n".join(emp_data["alerts"])
        full_text = f"{templates.get('title', '督办')}\n\n{greeting}\n{body}\n\n{templates.get('footer', '')}"
        results[emp_data["name"]] = full_text

        # Generate PS1 block
        if emp_id != "unassigned":
            safe_id = emp_id.replace('-', '_')
            ps1_lines.extend([
                "",
                f"Write-Host \"`n➤ 正在向 {emp_data['name']} ({emp_id}) 发送私聊消息...\" -ForegroundColor DarkGray",
                f"$msg_{safe_id} = @\"",
                full_text,
                "\"@",
                f"$out = welink-cli im send-to-user --receiver \"{emp_id}\" --text \"$msg_{safe_id}\" 2>&1 | Out-String",
                "if (-not [string]::IsNullOrWhiteSpace($out)) { Write-Host $out.Trim() }"
            ])

    ps1_lines.append("")
    ps1_lines.append("Write-Host \"`n✅ 全部分发任务已完成！\" -ForegroundColor Green")

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    if args.output_ps1:
        with open(args.output_ps1, "w", encoding="utf-8") as f:
            f.write("\n".join(ps1_lines) + "\n")
        print(f"✅ WeLink PowerShell script generated at {args.output_ps1}")

    print(f"✅ Expedite alerts generated for {len(results)} employees.")
    for emp_name, text in results.items():
        print(f"\n--- {emp_name} ---")
        print(text)

if __name__ == "__main__":
    main()
