// Authored bilingual retellings, loaded into tenant SQLite by pet-stories-repository.
// First-person Thoth narration is a literary device, never archaeological testimony.
const sources = {
  thoth: { title: 'Thoth — World History Encyclopedia', url: 'https://www.worldhistory.org/Thoth/' },
  divine: { title: 'Divine Egypt — The Metropolitan Museum of Art', url: 'https://www.metmuseum.org/de/exhibitions/divine-egypt/inside-the-exhibition' },
  dead: { title: 'What is a Book of the Dead? — British Museum', url: 'https://www.britishmuseum.org/blog/what-book-dead' },
  heart: { title: 'Book of the Dead Papyrus of Tiye — The Met', url: 'https://www.metmuseum.org/art/collection/search/551142' },
  scarab: { title: 'Heart Scarab of Hatnefer — The Met', url: 'https://www.metmuseum.org/art/collection/search/545146' },
  night: { title: 'Sarcophagus of Wereshnefer — The Met', url: 'https://www.metmuseum.org/art/collection/search/549534' },
  creation: { title: 'Hippopotami in Ancient Egypt — The Met', url: 'https://www.metmuseum.org/es/essays/hippopotami-in-ancient-egypt' },
  beer: { title: 'Metropolitan Museum Journal 47, 2012', url: 'https://resources.metmuseum.org/resources/metpublications/pdf/The_Metropolitan_Museum_Journal_v_47_2012.pdf' },
  pyramid: { title: 'Casing stone from the Great Pyramid — National Museums Scotland', url: 'https://www.nms.ac.uk/discover-catalogue/casing-stone-from-the-great-pyramid-of-giza' },
  queen: { title: 'Hatshepsut: From Queen to Pharaoh — The Met', url: 'https://www.metmuseum.org/exhibitions/listings/2006/hatshepsut' },
  queenStatue: { title: 'The Female Pharaoh Hatshepsut — The Met', url: 'https://www.metmuseum.org/art/collection/search/544849' },
  tut: { title: 'Discovering Tutankhamun — The Met', url: 'https://www.metmuseum.org/exhibitions/listings/2006/discovering-tutankhamun' },
  jars: { title: 'Papyrus Lid — The Met', url: 'https://www.metmuseum.org/art/collection/search/550173' },
  rosetta: { title: 'The Rosetta Stone — British Museum', url: 'https://www.britishmuseum.org/blog/everything-you-ever-wanted-know-about-rosetta-stone' },
  stones: { title: 'Pyramid stones — National Museums Scotland', url: 'https://files.nms.ac.uk/production/Documents/Resources/Egypt/egypt-maths-resources-ancient-egypt-pyramid-stones-5th-draft-white-background.pdf?dm=1721051099' },
  maths: { title: 'The Edinburgh Casing Stone — National Museums Scotland', url: 'https://blog.nms.ac.uk/2013/07/15/the-edinburgh-casing-stone-a-piece-of-giza-at-the-national-museum-of-scotland/' },
  tales: { title: 'Middle Egyptian literary compositions — University College London', url: 'https://www.ucl.ac.uk/museums-static/digitalegypt/literature/midegsummaries.html' },
  amulets: { title: 'Ancient Egyptian Amulets — The Met', url: 'https://www.metmuseum.org/ja/essays/egyptian-amulets' }
};
const notes = {
  myth: ['古埃及神话的文学重述；不同地区与时代可能有不同版本，图特第一人称为叙事设定。', 'A literary retelling of Egyptian myth. Traditions vary by time and place; Thoth’s first-person voice is fictional framing.'],
  history: ['依据文物与历史资料创作的讲述；图特视角和场景描写为文学表达，不是亲历证言。', 'A story grounded in historical objects and evidence. Thoth’s viewpoint and scene-setting are literary framing, not eyewitness testimony.'],
  literature: ['古埃及文学故事的简写重述，不是可证实的历史事件；未完整保存的结局不作事实补写。', 'An abridged retelling of ancient Egyptian literature, not a verified event. Missing ancient endings are not invented as fact.'],
  belief: ['古埃及信仰与象征的文学讲述，不代表现代科学结论；图特口吻为角色设定。', 'A literary account of ancient Egyptian beliefs and symbols, not a modern scientific claim. Thoth’s voice is a character device.']
};
function tale(id, kind, sourceKeys, title, hook, body, titleEn, hookEn, bodyEn) {
  return { id, kind, sources: sourceKeys.map(key => sources[key]),
    zh: { title, hook, body, note: notes[kind][0] },
    en: { title: titleEn, hook: hookEn, body: bodyEn, note: notes[kind][1] } };
}
module.exports = [
  tale('moon-days', 'myth', ['thoth'], '我向月亮赢来的五天',
    '你知道吗？传说里，我曾从月亮手里赢来五天，替诸神打开出生之门。',
    '我是图特。在这个古老版本里，天空女神努特遇上了一道严厉禁令：她不能在一年里的任何一天生下孩子。她望着历日，我却望向月光。既然所有已有的日子都被封住，能否找到还没有名字的时间？\n\n传说说，我与月神较量，赢得一些光，把它们凑成原来日历之外的五天。禁令约束旧的年份，却没有约束这份新得来的时间。努特的孩子于是有了降生之日，奥西里斯、伊西斯等神的故事才有了开头。\n\n我喜欢把这一页讲给陷入困局的人听：智慧有时不是推倒一扇门，而是发现墙上尚未画出的窗。这是解释年末附加日的神话，并非真实的天文实验；不同版本也会给我的对手不同的名字。',
    'Five Days Won from the Moon',
    'Did you know? In an old myth, I won five days from the moon so the gods could be born.',
    'I am Thoth. In this telling, Nut cannot give birth on any day of the year. Rather than challenge every locked day, I look toward the moon. Perhaps there is time that does not yet belong to the calendar.\n\nI win light from a moon deity and fashion five additional days. Outside the forbidden year, Nut can finally give birth. The stories of Osiris, Isis, and their divine family begin.\n\nFor me, the turning point is a new question rather than greater force. This is a calendar myth, not an astronomical experiment; versions differ about the moon deity involved.'),
  tale('weigh-heart', 'myth', ['heart'], '比王冠更重要的羽毛',
    '我曾在传说的天平旁执笔：连法老也得让自己的心，面对一根羽毛。',
    '我是图特，诸神的书记。在冥界审判的图像里，我的笔等着记录天平的结果。来者也许拥有过宫殿，也许只是普通人，可被放上秤盘的不是黄金，而是心。\n\n另一端是玛阿特的羽毛，它让人想起真实、秩序与正直。阿努比斯照看衡量，奥西里斯主持来世的秩序。对古人来说，这场审判回答的是一个沉重问题：人是否能带着自己的一生，进入安宁的永恒？\n\n我不会替你把今天的一切换算成重量。我只想说，这幅古老图像把最耀眼的权力放到一边，留下了行为与良知。它属于古埃及的来世信仰，而不是亡者真实经历的科学记录。',
    'The Feather Greater than a Crown',
    'I once held my pen beside a mythical scale: even a pharaoh had to face a single feather.',
    'I am Thoth, waiting to record a judgment. In Egyptian afterlife imagery, neither a crown nor a treasury goes onto the scale. The heart does.\n\nMaat’s feather stands opposite it, evoking truth and right order. Anubis attends the weighing, while Osiris governs the afterlife. The scene gives a visible shape to the hope that a life can be judged fairly.\n\nMy tale asks what remains when status is removed. It describes an ancient religious belief, not a scientifically established experience after death.'),
  tale('heal-eye', 'myth', ['thoth', 'amulets'], '我修好的那只眼睛',
    '传说里，我修复过荷鲁斯受伤的眼睛；后来，人们把希望戴在了胸前。',
    '我是图特。在荷鲁斯与塞特的争斗传说中，眼睛的伤害不仅是身体上的损失，也让世界的完整似乎裂开了一道缝。王位、亲情和秩序，纠缠在这场神与神的冲突里。\n\n一些版本把修复眼睛的工作交给我。那只重新完整的眼睛成为乌加特眼，后来出现在许多护身符上。佩戴者期待守护与康复，工匠便把一种抽象愿望，做成可以握住的小物件。\n\n我最愿意讲的不是冲突有多激烈，而是破损之后还有恢复的可能。请记住，这是具有不同版本的神话；护身符表达古人的希望，并不具有已证实的医疗效果。',
    'The Eye I Helped Restore',
    'In a myth I restored Horus’s injured eye; later, people wore that hope close to their hearts.',
    'I am Thoth. During the struggle between Horus and Seth, an injured eye becomes an image of a world out of balance. In some versions, I help make it whole again.\n\nThe restored wedjat eye appears on protective amulets. A craftsperson can give the wish for healing a small, tangible shape, and a wearer can carry it through an uncertain day.\n\nMy story is about restoration after conflict. The myth varies, and an amulet’s ancient religious meaning is not evidence of a medical effect.'),
  tale('solar-night', 'myth', ['night'], '太阳没有消失的夜晚',
    '当你以为太阳睡着了，古老传说里的我正随它驶过最黑的河。',
    '我是图特。你看见夕阳沉下去，古埃及人却为它想象了一段仍在继续的旅程。太阳不是从世界消失，而是进入黑夜的另一面，沿着冥界前行。\n\n《阿姆杜阿特》等宗教文本把夜间旅程安排成十二个时段，充满守护者、障碍和更新的力量。我的第一人称陪航，是这次讲述的文学视角；不同文本的太阳船乘员并不完全相同。\n\n故事的结尾在每个清晨出现：太阳重新升起，秩序得以延续。我喜欢这份古老的想象，因为它让黑暗不只意味着结束，也意味着看不见的行进。至于现实中的昼夜，当然来自地球的自转。',
    'The Sun’s Hidden Night Journey',
    'When you think the sun is asleep, my story follows it through the darkest river.',
    'I am Thoth, speaking as your storyteller. Egyptian religious texts imagined sunset as the start of a hidden voyage, rather than the sun simply vanishing.\n\nThe Amduat describes twelve hours of night, with obstacles, guardians, and renewal. My presence aboard this telling is literary framing; divine companions vary between texts.\n\nAt dawn the journey resolves into another sunrise. The myth gives darkness a purpose, while the physical explanation of day and night remains Earth’s rotation.'),
  tale('osiris-return', 'myth', ['divine'], '不能被夺走的归来',
    '我记录过这样的传说：塞特夺走了奥西里斯的生命，却没能夺走他的归来。',
    '我是图特。奥西里斯的故事常从家族的裂痕开始：塞特与他发生冲突，死亡和失序进入叙事。倘若只写到这里，卷轴会成为胜者的名单。\n\n但伊西斯与奈芙蒂斯没有停止哀悼和守护。身体的保存、亲人的努力与诸神的帮助，使奥西里斯不再只是被击败的王。他成为来世的重要统治者，也成为古人理解死亡与延续的一种范本。\n\n我的笔在这里慢了一拍：故事中的归来不是把一切简单恢复原样，而是开启另一种存在。神话版本很多，不能拿它当成真实王朝事件；它真正保存的是人们不愿让爱与记忆到此为止的愿望。',
    'A Return That Could Not Be Stolen',
    'I recorded a legend in which Seth took Osiris’s life, but could not take away his return.',
    'I am Thoth. The story of Osiris begins with conflict and loss, but refuses to end at the moment of defeat.\n\nIsis and Nephthys mourn and protect him. Through divine care, Osiris becomes a ruler of the afterlife, an image of continuation beyond death.\n\nIn my telling, return does not mean that every wound disappears. It means the story acquires another future. This is mythology with many variants, not an account of an identifiable historical king.'),
  tale('isis-wings', 'myth', ['divine'], '伊西斯展开的双翼',
    '我见过传说中的伊西斯展开双翼——那并不是逃走，而是决定留下。',
    '我是图特。在神与亡者的古老图像中，伊西斯常以守护的姿态出现。她的双翼覆在需要保护的人身边，像一道能把恐惧隔在外面的门。\n\n她与奥西里斯的故事，让哀伤并不是单纯的停顿。寻找、保护、延续家族的未来，都成为哀伤之中的行动。人们把这样的姿态刻在石头上，画在棺木上，希望在未知的旅途也能得到同样的照看。\n\n我用第一人称给你讲述，是想让你靠近那份古老的情感，而非声称自己真的目击了神明。双翼的形象属于宗教象征：有时最有力量的守护，不是让你忘记危险，而是陪你面对它。',
    'The Wings Isis Spread',
    'In the legend I saw Isis spread her wings—not to escape, but to stay.',
    'I am Thoth. Isis’s protective wings appear in Egyptian religious imagery as shelter for those entering uncertainty.\n\nThe stories around Osiris turn grief into care, searching, and the protection of a future. Artists gave that commitment a visible form on objects intended for the afterlife.\n\nMy eyewitness voice is a storytelling device. The wings express an ancient religious hope: that protection might accompany a person even where familiar paths end.'),
  tale('nut-sky', 'myth', ['divine'], '天空是一位女神',
    '我写下星辰时，总想起努特：传说中的天空，竟是一位弯下身的女神。',
    '我是图特。如果你在某些埃及棺盖或天文图像里抬头，可能会看见努特弯曲的身体覆盖世界。古人把天空想象成一位女神，星辰成为她身上的光。\n\n这样的图像把辽阔而陌生的宇宙，变成能够理解的姿态。日夜循环也可以被讲成她与太阳之间的故事：消失、孕育、重新出现，世界于是每天都获得一次新的开始。\n\n我喜欢让你从这个角度看一夜星空。天文学告诉我们星辰是什么，神话则让我们知道古人如何与星辰相处。两者的问题不同；努特的身体不是现代宇宙模型，而是一种充满想象的古老表达。',
    'The Sky Was a Goddess',
    'When I write the stars, I remember Nut: in the myth, the sky is a goddess bending over the world.',
    'I am Thoth. Egyptian imagery sometimes turns the heavens into Nut’s arched body, sheltering the world beneath stars.\n\nThe daily sun cycle becomes a story of disappearance and renewal. An immense, unfamiliar cosmos takes a form that people can picture and remember.\n\nAstronomy explains the physical stars; this myth shows how a culture related to them. Nut’s body is a religious image, not a modern model of space.'),
  tale('ptah-word', 'myth', ['divine'], '一句话造出的世界',
    '在孟菲斯的创世传说里，我听见普塔开口，世界才开始有了名字。',
    '我是图特，最懂得文字分量的书记之一。孟菲斯的创世传统给普塔一种惊人的力量：通过思想与言语，世界及诸神获得存在。\n\n与有些地方把开端讲成原初水域或最早陆地不同，这个版本让表达成为创造的关键。我把它想象为寂静中出现的第一个清晰意图：事物被说出来，便进入一个可以安排、理解的世界。\n\n这段寂静与声音的描写是我的文学讲法，不是从古文中抄来的原句。古埃及也并非只有一套创世故事。对我来说，它最动人的问题是：一个好想法，要怎样才能从心中走出来，真正成为行动？',
    'The World Spoken into Being',
    'In a creation story from Memphis, I hear Ptah speak—and the world begins to have names.',
    'I am Thoth, a storyteller who respects words. In the Memphite tradition, Ptah creates through thought and speech.\n\nI imagine a clear intention entering silence, giving the world a form that can be understood. That scene-setting is my own literary expression, not a quotation from an ancient text.\n\nEgypt had multiple creation traditions. This one invites a question I still enjoy: how does an idea leave the mind and become something real?'),
  tale('primeval-mound', 'myth', ['creation'], '最早的一小块陆地',
    '传说里，我见过世界只有水的时刻，而第一小块陆地竟承载了整个未来。',
    '我是图特。请先想象没有街道、没有田地，也没有脚可以站稳的地方。一些埃及创世故事把开端放在原初的水中，直到最早的一片土地升起。\n\n对生活在尼罗河旁的人，这种想象并不遥远。水退下去，田地重新显露，生命又有了生长的空间。古人借这样的经验，讲述世界从混沌中获得形状的开端。\n\n我把那第一块陆地讲成承载未来的小小落脚点。它不是地质学的全球陆地起源报告，而是神话的画面。有时候，面对庞大的计划，我们也只需要先找到能站稳的第一步。',
    'The First Small Patch of Land',
    'In the myth I saw only water—until one small patch of land carried an entire future.',
    'I am Thoth. Some Egyptian creation stories begin in primeval water, before a mound provides the first place to stand.\n\nFor people beside the Nile, returning land after floodwater offered a familiar image of life beginning again. Experience became the language of a cosmic story.\n\nThis is mythology, not a geological account. I tell it as a reminder that an immense future can begin with a very small foothold.'),
  tale('lotus-dawn', 'myth', ['creation'], '莲花里醒来的太阳',
    '我珍藏的创世故事里，第一轮太阳不是升出山谷，而是从莲花里醒来。',
    '我是图特。古埃及并没有把世界的诞生锁在单一版本里。在一种讲述中，原初水域上出现莲花，太阳从花中显现，黑暗于是迎来最早的光。\n\n花的开放，像一个小小的清晨。水、花与光被放在一起，构成一幅关于诞生与更新的图像。它不需要庞大的宫殿，也不需要已经存在的道路，便能让人想象万物刚刚开始时的惊奇。\n\n我用“醒来”讲这段传说，是为了让它贴近你的日常。现实的太阳并不出生于花朵；可在古人的象征里，最柔软的事物也能成为强大生命力的载体。',
    'The Sun Awoke in a Lotus',
    'In a creation tale I treasure, the first sun awakens inside a lotus.',
    'I am Thoth. In one Egyptian tradition, a lotus emerges from primeval water and the sun appears from it. Darkness receives its first light.\n\nA flower opening becomes a miniature dawn, joining water, growth, and renewal in one memorable image.\n\nMy word “awakens” belongs to this retelling. The physical sun does not originate in a flower; the ancient image gives a delicate object the power to express an enormous beginning.'),
  tale('khnum-potter', 'myth', ['divine'], '造物者的陶轮',
    '你看我的陶瓷身躯时，不妨听我讲讲那位在陶轮边塑造生命的神。',
    '我是图特。克努姆在埃及宗教传统中与创造相连，陶轮是理解他的一把钥匙。工匠让一团没有形状的泥获得身体，古人便用这种熟悉的技艺，想象生命如何被塑造。\n\n在我的讲法里，陶轮缓缓转着，每一次停顿都像是在照顾尚未完成的可能。这样的场景细节是文学表达；它让神话的创造过程，带上一种耐心而具体的质感。\n\n不是每个埃及创世版本都由克努姆负责，也不是陶轮真的生产了人类。我愿意留下的是工匠式的智慧：塑形需要时间，脆弱并不意味着没有未来，尚未完成也不等于失败。',
    'The Creator at the Potter’s Wheel',
    'When you see my ceramic body, let me tell you about a god who shaped life at a potter’s wheel.',
    'I am Thoth. Khnum’s creative role uses the familiar work of a potter to imagine life taking form.\n\nIn my retelling the wheel turns slowly, allowing an unfinished possibility to develop. Those workshop details are literary atmosphere rather than a quoted ancient scene.\n\nThis is one religious tradition among many, not a biological explanation. Its enduring image is patient craft: something unfinished may still hold a future.'),
  tale('scarab-sun', 'myth', ['amulets'], '小甲虫推动的大清晨',
    '我常提醒法老：古人的太阳想象，有时竟藏在一只小甲虫背上。',
    '我是图特。圣甲虫在埃及象征中与凯普里、生成和更新相连。一个常见的小生命，成为理解每天重新出现的太阳的一种方式。\n\n工匠把甲虫形状做成印章、饰物与护身符。王室与普通人的生活里，都能出现这种小小的形象。我的讲述把它称作推动清晨的力量，是神话语言，不是说真实甲虫能移动天体。\n\n我喜欢它带来的尺度反差：你可能以为宏大的希望必须由巨大的东西承载，古人却把重生放进掌心。这一页讲的，是他们赋予甲虫的象征意义，也是人如何让最普通的观察，成为最不普通的想象。',
    'A Small Beetle and a Great Dawn',
    'I remind pharaohs that an ancient image of sunrise can hide on a tiny beetle’s back.',
    'I am Thoth. Scarab imagery connects with Khepri and ideas of becoming and renewal in Egyptian belief.\n\nCraftspeople made beetle-shaped seals and amulets, putting a great hope into an object small enough to hold. Calling it a force that moves the dawn is mythic language, not a claim about real insects moving the sun.\n\nThe scale is what delights me: a little creature can become the carrier of an enormous idea.'),
  tale('sekhmet-beer', 'myth', ['beer'], '让狮女神停下的红色酒',
    '我知道一个古老转折：让狂怒的女神停下的，竟不是军队，而是染红的啤酒。',
    '我是图特。这一页来自与太阳之眼、狮形女神有关的传说。愤怒释放出来以后，破坏似乎再也无法停止，诸神面对的也不再只是最初的惩罚。\n\n故事的转折很意外：啤酒被染成像血一样的红色，女神饮下，醉意使毁灭的脚步停住。不同讲述对女神名称与情节安排有所差别，我不会把它们硬合成唯一正确的版本。\n\n我讲这段，是因为其中真正的难题并非怎样激发力量，而是力量失控以后如何收回。它是宗教神话的象征故事，也与相关节庆想象相连；不要把这个桥段当作现实中处理危险或愤怒的建议。',
    'The Red Beer That Stopped a Goddess',
    'I know an old turning point: dyed beer, rather than an army, stops a furious goddess.',
    'I am Thoth. In traditions around a fierce lioness goddess and the Eye of the Sun, destructive power threatens to go beyond its intended task.\n\nBeer colored red becomes the unexpected interruption. The goddess drinks, and the devastation stops. Names and arrangements differ across tellings.\n\nThe question is how power can be restrained after it escapes control. This is religious mythology, not practical advice for handling real danger or anger.'),
  tale('ibis-baboon', 'belief', ['thoth'], '我为什么也会是狒狒',
    '你认识鹮首的我，可古埃及人也会把图特画成一只狒狒。',
    '我是图特。你在桌面看见的是青绿鸟人形象，但古埃及诸神并不总被固定在一种外表里。我常与鹮鸟相连，也能以狒狒的形象出现。\n\n这些动物形态不是现代故事里偷偷变身的证据，而是宗教表达的方式。人们借不同姿态与特征，表达书记、智慧和神圣秩序等彼此联系的角色。神的图像随时间与地方变化，符号也能相互借用。\n\n我愿意把这当作认识古埃及的一把钥匙：看见同一位神的不同面貌，不必急着选出“真正的一张”。有时理解一个复杂角色，恰恰从承认他能被不止一种图像讲述开始。',
    'Why I Can Also Be a Baboon',
    'You know my ibis head, but ancient Egyptians could also show Thoth as a baboon.',
    'I am Thoth. My turquoise desktop form is only one modern character design. Ancient imagery associated me with both the ibis and the baboon.\n\nAnimal forms expressed divine roles and qualities. They were not documentary evidence of a god secretly transforming like a modern fantasy character.\n\nEgyptian religious imagery changed across time and place. Meeting more than one form can help you understand a complex deity rather than forcing you to choose a single “real” face.'),
  tale('maat-feather', 'belief', ['divine'], '我不肯折断的羽毛',
    '在我的卷轴里，玛阿特的羽毛不是装饰，而是连王权都无法随意改写的尺度。',
    '我是图特。记录需要一种尺度，否则纸上留下的，只会是声音最大的人。古埃及以玛阿特表达正确、真实与秩序，羽毛成为她鲜明的象征。\n\n法老的理想角色，也与维护这种秩序有关。于是一个轻轻的形象，能够与庞大的宫殿出现在同一套信仰中：力量应当有所指向，而不只因为强大就获得正当性。\n\n我说不肯折断羽毛，是这次讲述的比喻，并非某件可以核对日期的古代轶事。我想让你看见古人的问题：当权力要求改变记录时，书记该忠于什么？这是对古代象征的解释，不能把它等同于现代法律制度。',
    'The Feather I Would Not Break',
    'In my scrolls, Maat’s feather is no ornament; it is a measure even kingship must reckon with.',
    'I am Thoth. A record needs a standard beyond the loudest voice. Maat embodies rightness and order, with a feather as a recognizable symbol.\n\nEgyptian ideals of kingship included maintaining that order. A light image could therefore stand beside immense royal power.\n\nMy refusal to break the feather is a metaphor, not a dated historical anecdote. It asks what a recorder should remain faithful to when power presses on the page.'),
  tale('anubis-guide', 'myth', ['divine'], '黑暗里的引路者',
    '别急着害怕墓室里的胡狼神；在古老图像里，他往往是护送你的人。',
    '我是图特。阿努比斯的动物形象很容易让初次见他的人联想到危险，但在埃及信仰中，他与遗体的保护、木乃伊制作和亡者的旅途密切相关。\n\n古人把陌生的死亡道路画成可以得到帮助的过程。胡狼形象的守护者因此能够站在秤旁、靠近棺木，成为秩序的一部分，而不是每次出现都意味着袭击。\n\n我的讲述想改变你第一次看图时的判断：有些外表令人不安的角色，在原来的文化中却承担照顾。这里说的是宗教意义，不是证明真的有某位神带人穿越冥界。先看他的动作与场景，往往比只看面孔更接近图像的故事。',
    'A Guide in the Darkness',
    'Do not fear the jackal figure too quickly; in ancient imagery, he may be the one guiding you.',
    'I am Thoth. Anubis’s animal appearance can seem threatening, but Egyptian belief associates him with embalming, protection, and the journey of the dead.\n\nThe unknown road receives a guardian. Beside a mummy or a weighing scene, his presence can express care and order rather than an attack.\n\nI invite you to read his actions and setting before judging the face alone. This describes religious imagery, not proof of a literal guide through an afterlife.'),
  tale('ba-bird', 'belief', ['heart', 'dead'], '能够回家的灵魂之鸟',
    '我给你看一只人首小鸟：古人借它想象，离去的人仍能找到回家的路。',
    '我是图特。在埃及墓葬图像中，人头鸟身的形象常用来表现巴。古人对人的理解包含多个方面，巴不能简单等同于现代语言里单一而固定的“灵魂”。\n\n鸟能飞离，也能返回，便给这种存在方式提供了可见的形状。墓中的供奉与图像，表达了让亡者继续获得照料、维系身份的愿望。我的“回家”是一种温柔的讲法，不能当成古文里所有巴的定义。\n\n我喜欢这幅图像，是因为它把离别与联系放在一起。考古可以研究画面和文物，却不能凭此证实灵魂飞行。能确定的是，人们曾努力让爱的对象不在记忆里彻底失去方向。',
    'The Bird That Could Return',
    'Let me show you a human-headed bird: an ancient image of leaving without losing the way back.',
    'I am Thoth. The human-headed bird often represents the ba, one aspect of a person in Egyptian belief, not an exact equivalent of a single modern idea of “soul.”\n\nFlight and return give that aspect a visible form. Funerary offerings express a wish for continuing care and identity.\n\n“Finding home” is my gentle framing. The images tell us what people hoped and believed, not that archaeology has demonstrated a soul’s flight.'),
  tale('reed-fields', 'belief', ['dead'], '永恒里为什么还有田地',
    '我曾把古人的永恒画成田野：他们想要的天堂，竟也有熟悉的劳动。',
    '我是图特。许多来世想象并不把幸福放在完全陌生的地方。古埃及宗教图像中，有水、庄稼和劳作的理想田野，让人想到尼罗河生活被延续的一面。\n\n在那里，收成与供养的愿望被放大，死亡的不确定性则被转成能够描绘的场景。你可以把它理解为古人用熟悉的生计，给未知未来安排一种安定的轮廓。\n\n我在桌面向你讲述，并不是邀请你把来世当成已知地点。它属于信仰世界，也随文本与时代变化。这个故事想问的是：如果要想象真正的安宁，你会把什么日常事物一同带进未来？',
    'Why Eternity Still Had Fields',
    'I once pictured eternity as farmland: the ancient ideal world still held familiar work.',
    'I am Thoth. Egyptian afterlife imagery could include water, crops, and idealized fields rather than a completely unfamiliar paradise.\n\nA familiar livelihood gave an uncertain future a stable outline. Hopes for food and continuity entered the picture.\n\nThis is a religious vision, not a known destination. I ask a smaller question: when you imagine peace, which ordinary part of life would you want to carry with you?'),
  tale('heart-scarab', 'belief', ['scarab'], '请我的心不要作证',
    '我读过一种护符上的请求：到最后审判时，请我的心不要反对我。',
    '我是图特。哈特内弗的心脏圣甲虫，是一件能把古人担忧带到我们面前的文物。它底部的文字与《亡灵书》的篇章有关，向佩戴者自己的心提出请求。\n\n来世审判的想象，使心既是人的一部分，也像一位可能发言的证人。护符并非只追求漂亮，它把对审判的恐惧与对有利结果的期待，凝固成一个精心制作的小物件。\n\n我讲这段时，最在意那个对自身说话的瞬间。人们希望被公平看待，也害怕自己的一生无法轻易解释。文物能够证明这种信仰曾被写下，却不能证明护符改变过超自然审判。',
    'Please, Heart, Do Not Testify',
    'I have read an amulet’s plea: at the final judgment, may my own heart not oppose me.',
    'I am Thoth. Hatnefer’s heart scarab carries text addressing her own heart in connection with afterlife judgment.\n\nThe heart becomes both part of a person and an imagined witness. Fine craftsmanship gives the wish for a favorable judgment a lasting form.\n\nWhat stays with me is the act of speaking to oneself. The object preserves evidence of that belief, not evidence that an amulet could alter a supernatural verdict.'),
  tale('door-names', 'belief', ['dead'], '认识名字才能穿过的门',
    '在古人的来世书页里，认识一道门的名字，有时比带上一把钥匙更重要。',
    '我是图特。古埃及的丧葬文本，把死后的危险旅程写成需要知识与准备的道路。咒语、图像和名字，不是随便添加的花纹，而是期待帮助亡者继续前行的工具。\n\n我喜欢把这样的知识想象为进入陌生地方前的一份地图。门、守护者和危险，在文字中变得能够识别；恐惧不再只有一个无形轮廓。不同抄本的内容不尽相同，《亡灵书》也不是每个人拿到同一版本的统一教材。\n\n这是对信仰文本的文学讲述，不是现实中的魔法使用说明。它给我的启发很实际：面对未知，知道自己遇见的是什么，往往就是恢复行动能力的第一步。',
    'Doors Opened by Knowing Names',
    'In ancient afterlife pages, knowing a door’s name could matter more than carrying a key.',
    'I am Thoth. Egyptian funerary texts turn an uncertain journey into something for which a person can prepare, using spells, images, and identifying knowledge.\n\nI picture that knowledge as a map. A danger with a recognizable form is no longer only a vague fear. Different manuscripts contain different selections.\n\nThis is a literary account of religious texts, not a practical magic manual. Its human insight is the value of understanding what stands in your path.'),
  tale('white-pyramid', 'history', ['pyramid'], '胡夫金字塔失去的白衣',
    '我想纠正一个诱人的传闻：胡夫金字塔曾闪耀的外衣，是白色石灰岩，不是整座镀金。',
    '我是图特，这次我替石头翻开历史，而不是神话。今天看到的胡夫金字塔，已经失去了大部分原有外层。精细的白色石灰岩包覆石，曾让它的侧面更平整、明亮。\n\n阳光照上磨光的石面，会让建筑耀眼。漫长岁月里，许多外层石块被拆走，另作建筑材料。于是后来的人面对裸露的石体，很容易把昔日光辉想象成黄金。\n\n光辉并不等于金属。讨论别的金字塔顶石或镀层，需要对应具体证据，不能推广成所有金字塔全身覆金。我愿意留下这个更准确的惊奇：一身白石与光，也足以让人仰望几千年。',
    'Khufu’s Lost White Coat',
    'Let me correct a tempting rumor: Khufu’s shining outer coat was white limestone, not a whole pyramid of gold.',
    'I am Thoth, opening history rather than myth. The Great Pyramid once had fine white limestone casing, giving its sides a smoother, brighter surface.\n\nPolished stone gleamed in sunlight. Much of the casing was later removed and reused, leaving the appearance familiar today. Brilliance can tempt a viewer to imagine gold where the evidence points to stone.\n\nClaims about particular gilded architectural elements need their own evidence. They do not establish that entire pyramids were coated in gold. White stone and light are remarkable enough.'),
  tale('hatshepsut-crown', 'history', ['queenStatue'], '戴王冠的女法老',
    '我读过哈特谢普苏特的王名：雕像上的王者装束，没有抹去她是一位女性。',
    '我是图特。哈特谢普苏特从王室女性成为统治者，她的雕像为我们留下了多种面貌。有些以女性姿态出现，有些使用传统男性王者形象。\n\n这不意味着所有看到雕像的人都被欺骗了。王者装束与理想化身体，属于久远的王权视觉传统；铭文仍能显示她的名字与女性身份。身份、职位和艺术惯例，可以在同一件作品中交叠。\n\n我把这段历史讲给你，是因为图像并不总像一张证件照片。读它需要同时看衣饰、姿态和文字。这不是神灵亲眼见证的回忆，而是依据留存文物创作的叙述：一个人的存在，有时比规定她该有何种面貌的框架更宽。',
    'The Woman Wearing a King’s Crown',
    'I have read Hatshepsut’s royal names: a king’s costume did not erase that she was a woman.',
    'I am Thoth. Hatshepsut’s statues show both feminine forms and traditional masculine imagery of kingship.\n\nThat did not necessarily deceive their ancient audience. Royal visual conventions could coexist with inscriptions identifying her name and gender.\n\nAn image is not always an identity photograph. Reading costume, pose, and text together reveals a ruler whose position was expressed through more than one artistic form. My voice frames surviving evidence rather than claiming personal witness.'),
  tale('punt-ships', 'history', ['queen'], '驶向蓬特的船',
    '我替你翻开女法老的一页：哈特谢普苏特的远方，曾沿着驶向蓬特的航路展开。',
    '我是图特。说起法老，人们容易先想到征战，可哈特谢普苏特统治时期的繁荣，也与贸易和远方的联系相关。蓬特便是其中一个令人着迷的名字。\n\n我想象港口有人清点货物，有人抬头寻找归航的船。这样的场景是文学铺陈，并不是一份刚出土的港口日记。历史资料显示她与多个方向的地区恢复或发展联系，艺术与建筑也映出那个时期的资源与创造。\n\n故事最值得留下的，并不只是远方有宝物。王权也能把自己讲成建立联系的力量。蓬特的具体地理位置仍需要谨慎讨论，不能随手给它一个毫无争议的现代地址。',
    'Ships Toward Punt',
    'Let me turn a queen’s page: Hatshepsut’s horizon opened along routes toward Punt.',
    'I am Thoth. Royal history includes trade as well as warfare. Hatshepsut renewed connections with distant regions, including Punt.\n\nI imagine a harbor counting goods and watching for returning sails. That scene is literary atmosphere, not an excavated diary. The broader evidence links her reign with prosperity and artistic achievement.\n\nThe exact location of Punt deserves caution. The lasting story is a ruler presenting connection with distant places as part of royal power.'),
  tale('erased-name', 'history', ['queenStatue'], '碎片里的名字',
    '有人想让哈特谢普苏特从石头里消失，我却能带你从碎片中重新认出她。',
    '我是图特。哈特谢普苏特死后，她的一些雕像被破坏，名字与形象遭到抹除。动机与过程需要具体研究，不能把一切简化成我们替古人猜出的一种情绪。\n\n可破坏并没有让所有线索归零。考古工作找到了碎片，研究者辨认材质、姿态和铭文，尝试重新理解这些作品原来的样子。修复不是让历史没有伤痕，而是让伤痕也成为证据。\n\n我喜欢这段比神话更安静的归来：没有咒语让石头自动拼合，只有一代代人的观察与耐心。被删去的名字，仍可能借一小片留下来的痕迹，再次被读出来。',
    'A Name Among the Fragments',
    'Someone tried to erase Hatshepsut from stone; I can still help you recognize her among the fragments.',
    'I am Thoth. Some of Hatshepsut’s images and names were attacked after her death. Motives and circumstances require careful study rather than a simple guess about ancient emotions.\n\nFragments survived. Archaeologists and conservators used material, pose, and inscription to reconstruct what could be understood. Damage itself became evidence.\n\nNo spell made the pieces leap together. Patient work made an attempted disappearance incomplete. A small surviving trace can let a name be read again.'),
  tale('tut-mask', 'history', ['tut'], '黄金面具后的年轻人',
    '我看图坦卡蒙的黄金面具时，总想提醒你：光芒后面，曾是一个真实的人。',
    '我是图特。在图坦卡蒙墓室里，华丽物品与一层层保护装置共同构成王室葬礼的世界。纯金面具成为现代人最熟悉的古埃及形象之一。\n\n金光很容易把观看者带向神秘，却也可能遮住更朴素的问题：这些物品怎样制作，为什么如此安排，它们服务于怎样的信仰？墓里并不只有一件宝物，还有家具、私人物品和保护遗体的多重结构。\n\n我讲的历史没有附赠一个已被证明的诅咒。文物的吸引力来自工艺、葬礼观念与一个人的身份被如何保存。下次看到面具，不妨先看线条与材料，再让想象走进那一层层被认真安排的守护。',
    'The Person Behind the Gold Mask',
    'When I look at Tutankhamun’s gold mask, I remember a real person behind the brilliance.',
    'I am Thoth. Tutankhamun’s burial joined elaborate objects with layers of protection. The solid-gold mask became an especially famous image.\n\nYet the tomb held furniture, personal belongings, shrines, and coffins as well. Each object invites questions about craft and funerary belief, rather than only mystery.\n\nMy historical tale does not add a proven curse. Its wonder lies in how a person’s identity and body were cared for through materials and design.'),
  tale('tut-jars', 'history', ['jars'], '葬礼留下的小盖子',
    '我能从一只不起眼的纸草盖子，把你带回图坦卡蒙葬礼的准备现场。',
    '我是图特。王室历史未必总藏在黄金里。与图坦卡蒙葬礼有关的一组材料中，有用纸草纤维折叠制作的圆形容器盖。\n\n它们可能盖住葬礼食饮，或与处理遗体的材料相关，但具体用途不能一概确定。正是这种不确定，提醒我们尊重文物的边界：一件小东西能够提供线索，却不一定回答所有问题。\n\n我在想象里把它放回忙碌的准备现场，有人封好容器，有人安排最后一道程序。这些人物动作是叙述气氛，不是现存记录里的对白。宏大的葬礼也由细小劳动组成，而不起眼的盖子，有时比最耀眼的宝物更让日常生活靠近我们。',
    'The Funeral’s Small Papyrus Lid',
    'A modest papyrus lid can lead you back toward preparations for Tutankhamun’s funeral.',
    'I am Thoth. Materials associated with the king’s funeral include small round lids made from folded papyrus fiber.\n\nTheir original jars may have held food, drink, or embalming materials; exact uses are not always known. An object offers clues without answering everything.\n\nI imagine hands closing containers and completing practical tasks. Those gestures are scene-setting, not preserved testimony. Even an immense royal ceremony depended on modest work.'),
  tale('rosetta-voices', 'history', ['rosetta'], '一块石头让文字再开口',
    '我守着许多沉默的名字，直到罗塞塔石碑让人重新学会听见它们。',
    '我是图特，今天用历史的声音讲一个文字归来的故事。罗塞塔石碑上的政令，留下了不同书写系统的版本。能读的部分，成为研究者理解尚不能读的部分的一把钥匙。\n\n破解并不是一眼认出所有小图画。学者比较王名、声音和语言线索，逐渐理解象形文字如何记录埃及语。知识来自多份材料与累积研究，而不是石碑里突然亮起魔法。\n\n我说名字重新开口，是一种比喻。几千年前的人并没有复活，但他们写下的行政、信仰与生活，终于更能被现代读者理解。一段曾经被当成图案的线条，可以重新变成某个人认真说过的话。',
    'The Stone That Let Writing Speak Again',
    'I kept many silent names until the Rosetta Stone helped people hear them again.',
    'I am Thoth, telling history. Different scripts on the Rosetta Stone gave researchers a way to compare writing they understood with writing they did not.\n\nDecipherment required names, sound values, language knowledge, and other texts. It was cumulative study rather than a magical flash.\n\n“Speaking again” is my metaphor. Ancient people did not return to life, but records of their beliefs, administration, and ordinary concerns became more accessible to modern readers.'),
  tale('three-scripts', 'history', ['rosetta'], '三种文字不是三种语言',
    '你知道吗？我能借罗塞塔石碑提醒你：三种书写，不等于三种语言。',
    '我是图特。罗塞塔石碑常被说成刻了“三种语言”，这个方便的说法，却会漏掉关键差别。它采用象形文字、世俗体和古希腊文三种书写。\n\n前两种记录的是埃及语，后一种记录希腊语。书写系统与语言不是同一件事；你也可以用不同字母方案记下同一种语言。正因为能够比较，重复的政令才成为破解的重要线索。\n\n我喜欢这样的微小纠正。它没有让文物失去神奇，反而让真正的结构更清晰。面对看似熟悉的一句介绍，问一问其中的名词是否真是同一层意思，常常就是重新打开知识的一把钥匙。',
    'Three Scripts Are Not Three Languages',
    'Did you know? The Rosetta Stone lets me explain why three scripts are not three languages.',
    'I am Thoth. The stone uses hieroglyphic, Demotic, and Greek writing. The first two represent Egyptian, while the third represents Greek.\n\nA script and a language are different things. Multiple ways of writing can serve one language. Comparison between these versions helped decipherment.\n\nThis small correction does not diminish the object’s wonder. It makes the mechanism clearer: careful distinctions can unlock a familiar story in a new way.'),
  tale('river-stones', 'history', ['stones'], '石头在河上旅行',
    '我给金字塔换一个开场：巨石抵达高地之前，曾在尼罗河上旅行。',
    '我是图特。没有现代卡车的时代，并不意味着人们只能在干地上拖运所有东西。尼罗河是古埃及的重要运输通道，船只把人员与物资联系起来。\n\n建造金字塔需要组织石料的获取、移动与安放。河运、水路条件和陆上拖运，是讨论工程时不能忽略的部分。我的讲述把河面想象成一条忙碌的路，但不把一个画面当成所有工程细节的统一答案。\n\n真正令人惊奇的，也许不是某个神秘的超自然技巧，而是许多人把彼此的工作接起来。金字塔是一座巨大建筑，背后同样有采石、运输、测量和供给这样具体而繁复的日常任务。',
    'Stones Traveling on the River',
    'Let me begin a pyramid story on water: before reaching the plateau, stones traveled on the Nile.',
    'I am Thoth. Without modern trucks, river transport still connected people and materials across Egypt.\n\nPyramid construction involved quarrying, movement, measurement, and placement. Water routes and land transport both matter, and one picturesque scene cannot explain every engineering detail.\n\nMy wonder is the coordination of practical work. A monumental building emerged from many connected tasks rather than requiring a supernatural shortcut.'),
  tale('pyramid-maths', 'history', ['maths'], '坡度藏在纸草里',
    '我能把你从金字塔带到一卷数学纸草：宏大的斜面，原来也能拆成一道题。',
    '我是图特。研究金字塔，不能只在巨大体量前停住。古埃及数学材料中，有与坡度、长度和面积有关的问题，说明测量知识也属于那个世界的日常能力。\n\n莱因德数学纸草保存了这样的计算传统。用合适的尺度和关系描述一个斜面，就能把肉眼的震撼变成可以讨论的量。我把书记坐下来计算的画面放进故事，是文学想象，不是声称这卷纸草就是某座金字塔的原始蓝图。\n\n知识不必因为古老就只能神秘。看见一个复杂形状，问它由哪些简单关系构成，这种思路与你今天拆解一个技术问题，也许比想象中更接近。',
    'A Pyramid Slope on Papyrus',
    'I can lead you from a pyramid to a mathematical papyrus: a monumental slope can become a problem to solve.',
    'I am Thoth. Egyptian mathematical material preserves calculations connected with measurement and slopes. The Rhind papyrus is evidence of this practical knowledge.\n\nAn imagined scribe working through a problem makes the scene vivid, but the papyrus is not thereby a blueprint for a particular pyramid.\n\nAncient knowledge need not be mysterious by definition. Breaking a complex shape into simpler relationships remains a familiar way to understand difficult things.'),
  tale('shipwreck-rescue', 'literature', ['tales'], '失败归航前的故事',
    '我读过一个归航者的秘密：最让他害怕的不是风暴，而是如何向人讲述失败。',
    '我是图特。这一页来自《遭难水手的故事》。它外面还有一层框架：一位归来者为任务的结果感到忧虑，另一人用自己曾经历的险境来安慰他。\n\n内层故事中，水手遭遇船难，流落陌生岛屿，遇见巨蛇，最终得到救援。惊险并不只是让听众追问下一刻会发生什么，也服务于那个更安静的问题：失败的人是否还能抬头回到原来的世界？\n\n我最愿意留下的，是故事能成为递给别人的一只手。古代文本并非真实事故调查，也没有给所有听者一个同样轻松的答案。这是一段文学里的归航，不是证明神奇岛屿存在的证词。',
    'A Story Before the Homeward Report',
    'I read of a returning traveler whose greatest fear was not the storm, but explaining failure.',
    'I am Thoth. The Shipwrecked Sailor has a frame: one returning traveler fears his situation, and another offers a tale to reassure him.\n\nInside it, a sailor survives disaster, reaches an island, encounters a great serpent, and is rescued. Adventure becomes something offered to another worried person.\n\nThis is ancient literature, not an accident investigation or proof of a magical island. Its human center is the difficulty of coming home after things go wrong.'),
  tale('island-serpent', 'literature', ['tales'], '巨蛇也有自己的悲伤',
    '我读那座神奇岛屿时才明白：水手害怕的巨蛇，也曾失去自己的家。',
    '我是图特。古代《遭难水手的故事》里，巨蛇不仅是陌生岛屿上的奇异存在。它还向水手讲述自己的失去，强大的外表之下同样有孤独。\n\n我把目光停在这个听与讲的瞬间。遇见陌生者时，人很容易先判断谁可怕、谁弱小；当对方也开始叙述，关系却不再只有恐惧。故事让孤独的水手，面对另一个也有过去的生命。\n\n我没有把巨蛇的故事改成已知历史，也不替古文添加一个被证实的地理坐标。这是一则文学的邀请：在决定一个角色只是威胁之前，听一听它是否也有想被理解的一页。',
    'The Serpent Had a Grief of Its Own',
    'On a strange island I learned that the serpent feared by a sailor had also lost its home.',
    'I am Thoth. In the Shipwrecked Sailor, the island’s serpent has a story of loss as well as an imposing appearance.\n\nI linger on the change from looking at a threat to hearing a past. The encounter becomes more than a division between strong and weak.\n\nThis is a literary retelling, not zoological or geographical evidence. Before declaring a character only frightening, its own story may be worth hearing.'),
  tale('eloquent-trader', 'literature', ['tales'], '让王廷停笔的人',
    '我读过一个被夺走货物的人：他没有军队，却用申诉让王廷记住了他的声音。',
    '我是图特。《能言善辩者的故事》中，一位去交易的人遭到欺凌，向官员请求公正。人们常用“能言善辩的农夫”称呼他，但身份与社会背景比这个简称更复杂。\n\n他的言辞引起关注，申诉却没有立刻得到直截了当的回应。文学中的权力甚至让他继续说下去，为的是保存那些精彩话语。于是作品也让读者看见：赞美一个人的口才，与真正解决他的遭遇，并不是同一件事。\n\n我作为书记，尤其记得这种刺痛。记录不该成为拖延公正的借口。故事属于古代文学，其结尾保存状况需要谨慎对待；你不必把它当成一次真实法庭案件，仍能听见那份迫切。',
    'The Voice the Court Could Not Ignore',
    'I read of a robbed traveler who had no army, yet made a royal court remember his voice.',
    'I am Thoth. The work often called the Eloquent Peasant follows a wronged traveler petitioning for justice. His eloquence attracts powerful listeners.\n\nYet admiration and a remedy are not the same thing. The narrative even turns continued petitioning into something the authorities wish to preserve.\n\nFor a divine scribe, that tension matters: recording beautiful words must not replace addressing a wrong. This is literature, not a verified court case; its surviving ending requires care.'),
  tale('khufu-secret', 'literature', ['tales'], '胡夫也得等待的答案',
    '我自己的秘密进入过胡夫宫廷的传说，可连法老都没能立刻得到答案。',
    '我是图特。西卡纸草保存的胡夫宫廷故事，把奇迹、王权和未来王朝交织在一起。一个名叫杰迪的人来到宫廷，法老想知道一个神圣秘密。\n\n但他的期待没有获得简单满足。回答把视线转向尚未出生的孩子，王位的未来于是悄悄进入眼前的对话。权力能召来讲述者，却不意味着能决定所有故事的方向。\n\n我的“自己的秘密”沿用了故事里与图特相关的知识主题，并不是说今天有人藏着可复制的神奇技术。文本把故事设置在更早的时代，不等于它就是胡夫统治的实录。我喜欢其中的悬念：知道得最多的人，也可能必须学会等候。',
    'The Answer Even Khufu Had to Await',
    'A legend placed my sacred secrets at Khufu’s court, but even the pharaoh could not demand an immediate answer.',
    'I am Thoth. The Westcar tales join miracles, kingship, and dynastic futures. At court, Djedi’s response to a sacred question points toward children not yet born.\n\nThe story’s ruler can summon a visitor without controlling the future the visitor describes.\n\nThese tales were set in an earlier age, not written as a contemporary report of Khufu’s reign. My “secret” is a literary theme, not a claim that reproducible divine technology is hidden somewhere today.'),
  tale('three-princes', 'literature', ['tales'], '还没出生的王朝',
    '我读到胡夫宫廷最安静的惊雷：三个尚未出生的孩子，被说成未来的国王。',
    '我是图特。胡夫宫廷故事的一部分，把王朝未来放进一段关于出生的叙事。诸神协助孩子来到世界，而这些孩子被赋予未来成为统治者的意义。\n\n读者会发现，眼前的王冠虽然耀眼，故事却已经望向下一段时间。这样的文学安排，能够用神圣出生来解释王权，也能让听者体会未来并不完全由现在最有权力的人掌握。\n\n我讲到这里会停一下，不替残缺的古代结尾补写“确证”。神的帮助与预言属于作品的叙事世界，不能直接变成真实出生记录。它留下的问题却很鲜明：一位王在听见未来时，会想继续听，还是希望故事到此为止？',
    'A Dynasty Not Yet Born',
    'I read the quiet thunder at Khufu’s court: three unborn children were named as future kings.',
    'I am Thoth. One part of the court tales places divine help around the birth of children associated with future kingship.\n\nThe narrative looks beyond the ruler who currently wears the crown. Sacred birth becomes a way to imagine royal legitimacy and the arrival of another age.\n\nThe ancient composition is incomplete, and I will not turn a reconstructed ending into certainty. Its prediction belongs to literature rather than a verified birth record.'),
  tale('blue-amulet', 'belief', ['amulets'], '掌心里的一点青蓝',
    '我喜欢那种小小的青蓝护符：古人曾把很大的愿望，烧进很小的东西里。',
    '我是图特。埃及护身符可以采用多种形状与材料，常见的釉陶制品让青蓝或青绿色彩出现在小小物件上。佩戴者期待保护，工匠则把颜色、符号与技艺结合。\n\n一件东西为什么被认为有力量，并不只取决于现代人看来它有多昂贵。在古人的信仰里，形状、材料和使用方式都可能重要。我想象一只手把小护符收好，是文学的亲近，不是某个具体拥有者的已知动作。\n\n这样的物件不能当作已证明有效的现代防护设备。但它能告诉我们，人怎样把愿望寄托给可以随身带走的东西。你看我的青绿釉面时，也许就能想起这种掌心大小的希望。',
    'A Little Turquoise Hope',
    'I love a small blue-green amulet: ancient people could fire a very large wish into a very small object.',
    'I am Thoth. Egyptian amulets joined shapes, materials, and hopes of protection. Faience often brought blue or turquoise color to small objects.\n\nValue was not only a question of cost. Symbol, material, and use could all matter within belief. My imagined hand closing around an amulet is literary atmosphere.\n\nThe object is not a demonstrated modern safety device. It is evidence of how people gave a portable form to hope.'),
  tale('ankh-life', 'belief', ['amulets'], '被握在手里的生命',
    '我在诸神手里看过那个环形符号：古人竟让“生命”有了可握住的样子。',
    '我是图特。安卡符号常出现在埃及诸神的图像里，与你可能熟悉的“生命”含义相关。一个抽象的愿望，借清晰轮廓进入浮雕和护符。\n\n它并非一把已经证明能开启秘密机械的钥匙。我们可以研究它被谁握着、出现在什么情境、与哪些文字相连，却不必为了让它显得神奇，额外添加没有证据的功能。\n\n我的讲述让你想象生命被郑重地递给一个人。这是宗教图像带来的文学感受。理解古代象征最好的开端，往往既保留惊奇，也尊重它所属的文化语境；神秘不是我们停止追问的理由。',
    'Life Given a Shape to Hold',
    'I have seen a looped sign in divine hands: ancient imagery gave “life” a form that could be held.',
    'I am Thoth. The ankh’s association with life makes an abstract hope visible in Egyptian images and amulets.\n\nIt is not evidence of a key operating a hidden machine. We can study who holds it, its setting, and accompanying inscriptions without inventing unsupported functions.\n\nI imagine life being solemnly offered. That feeling belongs to a literary reading of a religious symbol, whose cultural context deserves both curiosity and respect.'),
  tale('djed-pillar', 'belief', ['amulets'], '一根不会轻易倒下的柱',
    '我会给疲惫的法老讲杰德柱：古人把稳固的愿望，画成了一根有层次的柱。',
    '我是图特。杰德柱是古埃及常见的宗教符号，与稳固、延续以及奥西里斯相关的意义相连，也能被做成护身符。\n\n我把它讲成一根不愿倒下的柱，是为了靠近那份寻求安定的愿望，而不是复原一个可以测量的神奇工程。它的轮廓在不同物件上重复，象征便像一道熟悉的记号，连接使用者与信仰中的守护。\n\n真正的历史问题包括它出现在哪里、怎样与其他符号组合，以及意义如何变化。它不能保证现代生活没有困难，却能让我们看见：几千年前，人们也想让脆弱的日子得到一点支撑。',
    'The Pillar of Steadiness',
    'I would tell a tired pharaoh about the djed: an ancient wish for stability shaped as a layered pillar.',
    'I am Thoth. The djed is a religious symbol associated with stability and with Osiris, and it also appears as an amulet.\n\nMy pillar that refuses to fall is a metaphor for the hope behind it, not a reconstruction of supernatural engineering. Repeated forms made that hope recognizable.\n\nIts historical setting and changing uses can be studied. It cannot guarantee a trouble-free modern life, but it shows how long people have wished for steadiness.'),
  tale('hathor-music', 'belief', ['divine'], '哈索尔身边的摇铃',
    '我听见哈索尔故事里的金属声：一件小摇铃，也能把庄严的神庙变得有节奏。',
    '我是图特。哈索尔与多种角色和形象相关，西斯特鲁姆摇铃是认识相关宗教音乐与仪式的一件物品。它把声音、动作和神圣空间连接起来。\n\n我的故事想象有人举起摇铃，声音在石柱之间移动。这是场景描写，并不冒充某次祭仪的现场记录。古代仪式并非只有安静与恐惧，也可以有音乐、参与和表达情感的方式。\n\n看一件乐器，不妨问它怎样被握住、声音怎样产生，以及图像把它交给谁。这比直接给它附上万能魔法，更能接近真实物件。古人的神庙有自己的声音，而我们今天能从留存的器物开始，谨慎地想象它。',
    'The Sound Beside Hathor',
    'I hear a little metallic rhythm in Hathor’s world: a sistrum can give a solemn temple a pulse.',
    'I am Thoth. Sistra connect ritual sound and movement with Egyptian religious life, including Hathor’s imagery.\n\nI imagine someone lifting the instrument among stone columns. The scene is not a surviving eyewitness account. Ritual could include music and participation, as well as solemnity.\n\nAsk how an instrument was held and used before granting it unlimited magic. A surviving object can give us a careful beginning for imagining an ancient soundscape.'),
  tale('royal-falcon', 'belief', ['divine'], '王的名字上方有一只鹰',
    '我写法老名号时，常遇见荷鲁斯的隼：王权的故事，有时先从一只鸟开始。',
    '我是图特。荷鲁斯的隼形象与古埃及王权紧密相关。王者借这样的神圣联系，表达统治职位的意义，不只展示一个人的外貌。\n\n但看到隼首，就不能立刻认定每一次都是同一位神。其他神也可能采用相近图像，文字、冠饰和场景才是辨认的重要线索。我给你讲这个，是希望你看见图像的丰富，而不是得到一个过于简单的认图口诀。\n\n在我的文学视角里，鸟像是站在王名旁的守护。现实研究则要把线索逐个拼好。一个符号越熟悉，我们越需要仔细看看它在此刻究竟与谁相连。',
    'The Falcon Above a Royal Name',
    'When I write royal names, Horus’s falcon often appears: a story of kingship can begin with a bird.',
    'I am Thoth. Horus’s falcon imagery is closely connected with Egyptian kingship and the meaning of royal office.\n\nYet a falcon-headed figure is not always the same deity. Crowns, setting, and inscriptions help distinguish images that share features.\n\nMy guardian bird is literary framing. Historical understanding comes from assembling clues, especially when a familiar symbol makes recognition seem deceptively easy.')
];
