/* Encrypted portable NetCare configuration backup. Keys and passwords stay inside the embedded extension form. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory;else root.createNetcareBackup=factory;})(typeof globalThis!=='undefined'?globalThis:this,function createNetcareBackup(){
  const limit=16*1024*1024, encoder=new TextEncoder(),decoder=new TextDecoder();
  const allowed=k=>['netcareExtractionSettings','netcareAiModels','netcareAiSelectedModel','netcareStorageSettings','f12PopupLanguage'].includes(k);
  const configuration=data=>{if(!data||typeof data!=='object'||Array.isArray(data))throw Error('备份内容无效 / Invalid backup content');return Object.fromEntries(Object.entries(data).filter(([k])=>allowed(k)));};
  const bytesTo64=bytes=>{let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);};
  const from64=s=>{if(typeof s!=='string'||s.length>24*1024*1024||!/^[A-Za-z0-9+/]*={0,2}$/.test(s))throw Error('备份编码无效 / Invalid encoding');return Uint8Array.from(atob(s),c=>c.charCodeAt(0));};
  const key=async(password,salt)=>{if(typeof password!=='string'||password.length<8||password.length>1024)throw Error('备份密码至少8位 / Password requires 8 characters');const material=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);};
  const validate=(data,validSettings,modelRequest)=>{
    if(!data||typeof data!=='object'||Array.isArray(data)||JSON.stringify(data).length>limit||Object.keys(data).some(k=>!allowed(k)))throw Error('备份内容或字段无效 / Invalid backup fields');
    if(data.f12PopupLanguage!=null&&!['zh','en'].includes(data.f12PopupLanguage))throw Error('Invalid language');
    if(data.netcareStorageSettings&&(!Number.isInteger(data.netcareStorageSettings.bytes)||data.netcareStorageSettings.bytes<50*1024*1024||data.netcareStorageSettings.bytes>2048*1024*1024))throw Error('Invalid storage capacity');
    if(data.netcareExtractionSettings&&!validSettings(data.netcareExtractionSettings))throw Error('章节配置无效 / Invalid settings');
    if(data.netcareAiModels){if(!Array.isArray(data.netcareAiModels)||data.netcareAiModels.length>20||new Set(data.netcareAiModels.map(m=>m.id)).size!==data.netcareAiModels.length)throw Error('模型列表无效');for(const m of data.netcareAiModels){if(typeof m.id!=='string'||m.id.length>100||typeof m.name!=='string'||m.name.length>200||typeof m.url!=='string'||typeof m.model!=='string'||typeof m.protocol!=='string'||m.key!=null&&typeof m.key!=='string')throw Error('模型信息无效');modelRequest(m,'test');}}
    if(data.netcareAiSelectedModel!=null&&(typeof data.netcareAiSelectedModel!=='string'||data.netcareAiSelectedModel&&!data.netcareAiModels?.some(m=>m.id===data.netcareAiSelectedModel)))throw Error('审计模型不存在');
    return data;
  };
  return {allowed,configuration,validate,async encrypt(data,password){const plain=encoder.encode(JSON.stringify(configuration(data)));if(plain.length>limit)throw Error('备份超过16MB');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:encoder.encode('netcare-rfc-backup:3')},await key(password,salt),plain);return JSON.stringify({format:'netcare-rfc-backup',version:3,scope:'configuration',createdAt:new Date().toISOString(),encryption:{cipher:'AES-256-GCM',kdf:'PBKDF2-SHA256',iterations:210000,salt:bytesTo64(salt),iv:bytesTo64(iv)},ciphertext:bytesTo64(new Uint8Array(cipher))},null,2);},async decrypt(text,password){if(typeof text!=='string'||text.length>24*1024*1024)throw Error('备份超过24MB');let b;try{b=JSON.parse(text);}catch{throw Error('无效JSON');}if(b.format==='netcare-rfc-settings'&&b.version===1)return {netcareExtractionSettings:b.settings};const e=b.encryption;if(b.format!=='netcare-rfc-backup'||![2,3].includes(b.version)||b.version===3&&b.scope!=='configuration'||e?.cipher!=='AES-256-GCM'||e.kdf!=='PBKDF2-SHA256'||e.iterations!==210000)throw Error('不支持的备份版本');const salt=from64(e.salt),iv=from64(e.iv);if(salt.length!==16||iv.length!==12)throw Error('加密参数无效');try{const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:encoder.encode('netcare-rfc-backup:'+b.version)},await key(password,salt),from64(b.ciphertext));if(plain.byteLength>limit)throw Error();return configuration(JSON.parse(decoder.decode(plain)));}catch{throw Error('密码不正确或文件损坏，未更改配置 / Wrong password or damaged backup');}}};
});
