(function initF12ExtensionPacker(root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  if (root) root.F12ExtensionPacker = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function createPackerApi() {
  "use strict";

  const DEFAULT_PERMISSIONS = ["storage", "activeTab", "scripting"];
  const OPTIONAL_PERMISSIONS = new Set([
    "alarms", "clipboardRead", "clipboardWrite", "cookies", "downloads",
    "notifications", "tabs", "webNavigation"
  ]);
  const RUN_AT_VALUES = new Set(["document_start", "document_end", "document_idle"]);
  const WORLD_VALUES = new Set(["MAIN", "ISOLATED"]);

  function unique(values) {
    return [...new Set(values)];
  }

  function parseList(value) {
    if (Array.isArray(value)) return unique(value.map(String).map(item => item.trim()).filter(Boolean));
    return unique(String(value || "").split(/[\n,]+/).map(item => item.trim()).filter(Boolean));
  }

  function isValidVersion(version) {
    const parts = String(version || "").split(".");
    return parts.length >= 1 && parts.length <= 4 && parts.every(part => {
      if (!/^\d+$/.test(part)) return false;
      if (part.length > 1 && part.startsWith("0")) return false;
      const value = Number(part);
      return Number.isSafeInteger(value) && value >= 0 && value <= 65535;
    });
  }

  function isValidMatchPattern(pattern) {
    if (pattern === "<all_urls>") return true;
    const match = /^(\*|http|https|file):\/\/([^/]*)\/(.*)$/.exec(pattern);
    if (!match) return false;
    const [, scheme, host] = match;
    if (scheme === "file") return host === "";
    if (host === "*") return true;
    if (host.startsWith("*.")) return /^\*\.[^*\s/:]+(?:\.[^*\s/:]+)+(?:\:\d+)?$/.test(host);
    return host.length > 0 && /^[^*\s/]+$/.test(host);
  }

  function analyzeCode(code) {
    const source = String(code || "");
    const errors = [];
    const warnings = [];
    const suggestions = [];

    if (!source.trim()) {
      warnings.push("脚本为空，将生成一条加载日志作为 content.js。");
      return { errors, warnings, suggestions };
    }

    try {
      // Content scripts are classic scripts, so Function is a useful syntax compatibility check.
      // It intentionally rejects top-level await/import/export just like content.js would.
      new Function(source);
    } catch (error) {
      errors.push(`脚本无法作为传统 content.js 解析：${error.message}`);
    }

    if (/\b(?:\$0|\$1|\$2|\$3|\$4|copy|inspect|monitor|unmonitor|queryObjects)\s*\(/.test(source)) {
      warnings.push("检测到 DevTools Console 专用命令（如 $0/copy/inspect），扩展环境中不可直接使用。");
    }
    if (/\bGM_[A-Za-z0-9_]+\b|\bunsafeWindow\b/.test(source)) {
      warnings.push("检测到油猴/Tampermonkey API；浏览器扩展不会自动提供 GM_* 或 unsafeWindow。");
    }
    if (/\b(?:eval|new\s+Function)\s*\(/.test(source)) {
      warnings.push("检测到动态代码执行；可能受到页面 CSP 或扩展安全策略限制。");
    }
    if (/(?:createElement\s*\(\s*["']script["']|\.src\s*=)\s*[\s\S]{0,160}https?:\/\//i.test(source)) {
      warnings.push("检测到远程脚本加载；目标网站 CSP 可能阻止加载，发布到扩展商店时也需要额外审查。");
    }
    if (/\bchrome\.downloads\b/.test(source)) suggestions.push("脚本使用 chrome.downloads，建议增加 downloads 权限。");
    if (/\bchrome\.cookies\b/.test(source)) suggestions.push("脚本使用 chrome.cookies，建议增加 cookies 权限。");
    if (/\bchrome\.notifications\b/.test(source)) suggestions.push("脚本使用 chrome.notifications，建议增加 notifications 权限。");
    if (/\bchrome\.tabs\b/.test(source)) suggestions.push("脚本使用 chrome.tabs；该 API 通常应放在 Popup 或后台脚本中，并可能需要 tabs 权限。");

    return { errors, warnings, suggestions };
  }

  function normalizeOptions(options) {
    const input = options || {};
    const matches = parseList(input.matches || input.matchPattern || "*://*/*");
    const optionalPermissions = parseList(input.optionalPermissions)
      .filter(permission => OPTIONAL_PERMISSIONS.has(permission));
    return {
      name: String(input.name || "My Extension").trim(),
      version: String(input.version || "1.0.0").trim(),
      description: String(input.description || "Generated by F12 Packer").trim(),
      matches,
      world: WORLD_VALUES.has(input.world) ? input.world : "MAIN",
      runAt: RUN_AT_VALUES.has(input.runAt) ? input.runAt : "document_idle",
      allFrames: input.allFrames === true,
      includePopup: input.includePopup !== false,
      optionalPermissions,
      code: String(input.code || "")
    };
  }

  function validateOptions(options) {
    const normalized = normalizeOptions(options);
    const errors = [];
    if (!normalized.name) errors.push("扩展名称不能为空。");
    if (normalized.name.length > 75) errors.push("扩展名称不能超过 75 个字符。");
    if (normalized.description.length > 132) errors.push("扩展描述不能超过 132 个字符。");
    if (!isValidVersion(normalized.version)) errors.push("版本号必须由 1–4 段 0–65535 的整数构成，例如 1.0.0。段不能有前导零。");
    if (!normalized.matches.length) errors.push("至少需要一个匹配网址。");
    normalized.matches.forEach(pattern => {
      if (!isValidMatchPattern(pattern)) errors.push(`无效的匹配网址：${pattern}`);
    });
    const analysis = analyzeCode(normalized.code);
    return {
      options: normalized,
      errors: [...errors, ...analysis.errors],
      warnings: analysis.warnings,
      suggestions: analysis.suggestions
    };
  }

  function escapeHtml(value) {
    return String(value).replace(/[&<>"']/g, char => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;"
    })[char]);
  }

  function buildPackage(options) {
    const validation = validateOptions(options);
    if (validation.errors.length) {
      const error = new Error(validation.errors.join("\n"));
      error.validation = validation;
      throw error;
    }
    const settings = validation.options;
    const permissions = unique([...DEFAULT_PERMISSIONS, ...settings.optionalPermissions]);
    const contentScript = {
      matches: settings.matches,
      js: ["content.js"],
      run_at: settings.runAt,
      world: settings.world
    };
    if (settings.allFrames) contentScript.all_frames = true;

    const manifest = {
      manifest_version: 3,
      name: settings.name,
      version: settings.version,
      description: settings.description,
      permissions,
      host_permissions: settings.matches,
      content_scripts: [contentScript]
    };
    const files = {
      "manifest.json": JSON.stringify(manifest, null, 2),
      "content.js": settings.code.trim() ? settings.code : `console.log("[${settings.name.replace(/["\\]/g, "\\$&")}] Content script loaded!");`
    };

    if (settings.includePopup) {
      manifest.action = { default_title: settings.name, default_popup: "popup.html" };
      manifest.background = { service_worker: "background.js" };
      files["manifest.json"] = JSON.stringify(manifest, null, 2);
      files["popup.html"] = `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(settings.name)}</title>
  <link rel="stylesheet" href="popup.css">
</head>
<body>
  <main class="panel">
    <h1>${escapeHtml(settings.name)}</h1>
    <p id="status">请先打开目标网页</p>
    <button id="startButton">启动监控</button>
    <button id="stopButton" class="secondary">终止监控</button>
  </main>
  <script src="popup.js"><\/script>
</body>
</html>`;
      files["popup.css"] = `* { box-sizing: border-box; }
body { width: 260px; margin: 0; padding: 12px; color: #172033; font-family: "Microsoft YaHei", "Segoe UI", sans-serif; background: #f3f6f9; }
.panel { padding: 14px; border-radius: 14px; background: #fff; box-shadow: 0 4px 12px rgba(0,0,0,0.05); }
h1 { margin: 0 0 8px; font-size: 17px; }
p { min-height: 32px; margin: 0 0 12px; color: #667085; font-size: 11px; }
button { width: 100%; margin-top: 7px; padding: 9px 10px; border: 0; border-radius: 9px; color: #fff; background: #1677ff; cursor: pointer; transition: background 0.2s; }
button:hover { background: #0958d9; }
button.secondary { color: #fff; background: #ff4d4f; }
button.secondary:hover { background: #cf1322; }`;
      files["popup.js"] = `async function getActiveTab() {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  return tab;
}

async function sendToPage(action) {
  const tab = await getActiveTab();
  if (!tab?.id) {
    document.getElementById("status").textContent = "无法获取当前页面";
    return;
  }
  try {
    await chrome.scripting.executeScript({
      target: { tabId: tab.id },
      world: "MAIN",
      func: (pageAction) => {
        window.postMessage({ source: "EXTENSION_POPUP", action: pageAction }, "*");
      },
      args: [action]
    });
    document.getElementById("status").textContent = action === "START" ? "监控已启动！" : "监控已终止！";
  } catch (err) {
    document.getElementById("status").textContent = err.message.includes("Cannot access")
      ? "无法在系统页面(edge://等)运行，请打开目标网页"
      : "执行失败: " + err.message;
  }
}

document.getElementById("startButton").addEventListener("click", () => sendToPage("START"));
document.getElementById("stopButton").addEventListener("click", () => sendToPage("STOP"));`;
      files["background.js"] = `chrome.runtime.onInstalled.addListener(() => {
  console.log(${JSON.stringify(`${settings.name} extension installed successfully.`)});
});`;
    }

    return { manifest, files, validation };
  }

  return {
    DEFAULT_PERMISSIONS,
    analyzeCode,
    buildPackage,
    isValidMatchPattern,
    isValidVersion,
    parseList,
    validateOptions
  };
});
